[package]
name = "discord-token-grabber"
version = "1.0.0"
edition = "2018"
authors = ["FssAy"]
publish = false

[dependencies]
regex = "1.3.9"
encoding = "0.2.33"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true